### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by dee-y** [nivocart/nivocart#1]
Hello, i am a graphic designer who loves contributing to open source. Would you like me to contribute a logo to your project? it's totally free of course.

**Comment by nivocart** [comment]
@dee-y 
Yes please! A professionally designed NivoCart logo would be wonderful!
Two favicons would be nice too, one for Admin and one for Catalog.
Thank you for wanting to contribute to the project. Much appreciated.

**Comment by dee-y** [comment]
Hi what do you think of this design? second variation has rounded corners. The design is a representation of letter "N" inside shopping cart.

![nivocart-01](https://user-images.githubusercontent.com/36637989/47666156-244d5480-dba3-11e8-95b1-00b94c7bd963.png)

**Comment by dee-y** [comment]
And here is the mockup on site

![screenshot 654](https://user-images.githubusercontent.com/36637989/47666268-6a0a1d00-dba3-11e8-8008-08e3ded4c779.png)

**Comment by nivocart** [comment]
I prefer the second one with rounded corners ... but overall not original enough.
Something else is needed, something more futuristic, showing things like speed, reliability, security, ...
Something highly recognizable.

**Comment by nivocart** [comment]
@dee-y 
Any update on your progress?

**Comment by dee-y** [comment]
yes, update 2

![untitled-1-01](https://user-images.githubusercontent.com/36637989/48305569-5c528100-e52d-11e8-9679-fabc002a4d45.png)

**Comment by nivocart** [comment]
Nice! Much more original!
Still a bit of tweaking to do but we are almost there.
I think the cart itself is too big (high) in proportion with the wheels.
Also a shallower curve at the front would accentuate the "speed" effect.
Maybe give the cart handle the look of a sports car "spoiler" ...
Good job man!

**Comment by dee-y** [comment]
Thanks for the pointers, feel there is positive improvement also. I added the curve, but the spoilers seem to not fit the design so i improvised. I also added a variation with italics font type to accentuate the curve. What do you think?
![nivocart1-02](https://user-images.githubusercontent.com/36637989/48318415-f3d4d400-e600-11e8-9bc5-8c66672fec65.png)

**Comment by nivocart** [comment]
Better again.
I have made one of my own to show you what I have in mind.
What do you think? Can we improve ?
![nivocart_logos](https://user-images.githubusercontent.com/41955237/48351010-d0ea0480-e680-11e8-85e7-7331782ac6c5.png)

**Comment by dee-y** [comment]
Update
![nivocart1x-01](https://user-images.githubusercontent.com/36637989/48984732-e3901f00-f0ff-11e8-8217-24ab6baeb141.png)

**Comment by nivocart** [comment]
Nice but I am still not convinced. Somehow it doesn't feel right. I dunno what to say ...
