### ISSUE TITLE
Download Invoice Issue

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#18]
Please note that there's an issue with downloading invoices from the **User Account > Order History**.
When downloading the **pdf** invoice you get this:
![PDF](https://user-images.githubusercontent.com/3336728/63217842-f64af800-c155-11e9-8949-9effdddaab8f.jpg)

You can test more [here](http://demo.nivocart.com/).
**User:** demo@nivocart.com 
**Pass:** demo

Also I got the error below, I don't know if it's related:
`2019-08-17 15:14:20 - PHP Notice: Undefined index: token in C:\Bitnami\wampstack-7.0.33-0\apache2\htdocs\nivo\catalog\controller\account\order.php on line 721`

Tested on: https://github.com/nivocart/nivocart/commit/18b306c2d689eef165b31fa0a2eace9bc86262eb
PHP 7.0.33

**Comment by nivocart** [comment]
I made some corrections in DomPDF library.
It now works here for me.
Let me know if I can close this.

**Comment by Tangol** [comment]
Issue fixed.

One more thing: the downloaded pdf invoice is named **Order-Information-#.pdf** .
Can you please modify it to **Invoice-#.pdf** ?

Thanks!

**Comment by nivocart** [comment]
I've changed it to "Invoice Copy":
Admin file: Invoice-#
Customer file: Invoice-Copy-#
I think this makes perfect sense.
