### ISSUE TITLE
Order Status Issue

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#19]
At **Sales > Orders > View > History** we can't change the **Order Status**.
Nothing happens when you click on **Add History**.

You can test [here](http://demo.nivocart.com/admin/).
demo / demo

Tested on: https://github.com/nivocart/nivocart/commit/18b306c2d689eef165b31fa0a2eace9bc86262eb
PHP 7.0.33

**Comment by nivocart** [comment]
This issue should be resolved now.
Thank you for reporting it.
Let me know.

**Comment by Tangol** [comment]
Issue fixed.
Can be closed.

Thanks!
