### ISSUE TITLE
Errors on page

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#20]
Go to http://demo.nivocart.com/index.php?route=product/product&product_id=1 and inspect element on the page.
In the console you'll see 2 errors:
![err](https://user-images.githubusercontent.com/3336728/63218036-04027c80-c15a-11e9-9821-97b8074f3914.jpg)

Tested with **Firefox 68.0.2**

**Comment by nivocart** [comment]
I updated jQuery timepicker to latest.
Let me know if this issue is fixed.

**Comment by Tangol** [comment]
Still getting the error, different line of code.
![err1](https://user-images.githubusercontent.com/3336728/63228520-bc80fc80-c1fc-11e9-8ccb-a6aa30bf5633.jpg)

Tested on: https://github.com/nivocart/nivocart/commit/f8cf750b9db93ea50890c61fae99b8776ec31333

**Comment by nivocart** [comment]
Please check again.
There is no error on my side with the new files, which now clearly define "ui" properly.

**Comment by Tangol** [comment]
Issue fixed.
Can be closed.

Thanks!
