### ISSUE TITLE
Remove button text underline

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#22]
We should remove the underline from the **accept cookie button** as it looks bad.

![under](https://user-images.githubusercontent.com/3336728/63229878-cbbc7600-c20d-11e9-9c07-f2e2c3acfbc1.jpg)

Thanks!

**Comment by nivocart** [comment]
I tried to fix that a long time ago but sadly I can't.
The reason is this is a link, so the browsers underline it by default.
On top of that the button is embedded into a javascript which make this even harder to modify.
So I don't think I will be able to change this.

**Comment by Tangol** [comment]
Then how come http://nivocart.com/ doesn't have this issue?

![nivo](https://user-images.githubusercontent.com/3336728/63651154-a9b97b00-c75a-11e9-8882-717bfcfa73e7.jpg)
