### ISSUE TITLE
Optimization needed

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#4]
Comparing NivoCart with OpenCart Overclocked, you'll see that Overclocked performs better.
![speed](https://user-images.githubusercontent.com/3336728/48866027-08238880-edda-11e8-9499-fdc5a97b7092.jpg)

- https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdemo.nivocart.com%2Findex.php 

- https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdemo.villagedefrance.net%2Findex.php

Tested on https://github.com/nivocart/nivocart/commit/156d48f811fdcc0661f4e2a03c609b443362e8be

**Comment by nivocart** [comment]
Interesting comparison but I need to point out a couple of things:

First, the 2 Demo sites are on a different server.
Second, the Demo Data images are much larger and better quality.
Third, All the stylesheets are now loading the extended Roboto font.

I already did some work on performances by reducing the number of requests significantly from 64 to 49 but, as you can see, the page size is almost 3 times larger.

I guess there will always be a trade-off between Quality and Speed.
I will try to improve further on this but no guarantees. Suggestions are welcome.

**Comment by Tangol** [comment]
**Google Chrome Developer Tools** offers some great insight about what can be optimized:

For example, pick a page (http://demo.nivocart.com/) and **Inspect > Audits > Check All > Run audits**.

**Comment by nivocart** [comment]
Thanks for the Google Dev link.
I think most issues are now solved.
I don't think I can optimize the images constructively across all pages.
So for me this issue is resolved.
