### ISSUE TITLE
jQuery Migrate

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#7]
Please note that **jQuery Migrate** still gets loaded on every page.
It shouldn't be necessary anymore, right?

https://github.com/nivocart/nivocart/search?q=jquery+migrate&unscoped_q=jquery+migrate

Tested on https://github.com/nivocart/nivocart/commit/90c68a70b6b9a1f5a6ef3d54ca4e3b6742e6668c

**Comment by nivocart** [comment]
Technically you're right, we don't really need it, but I want to leave it to allow compatibility with some older OC extensions that people may want to convert for NivoCart.
It is just a fail safe.
