### ISSUE TITLE
SEO URL Issue

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#8]
I've activated both **SEO URLs** and **Automatic SEO URLs** and when I try to access **Category, Product, Manufacturer, Information, News** I get the following error:

![livesearch](https://user-images.githubusercontent.com/3336728/49395391-fe394800-f73e-11e8-93da-a6d279a4298b.png)

Tested on https://github.com/nivocart/nivocart/commit/90c68a70b6b9a1f5a6ef3d54ca4e3b6742e6668c

**Comment by nivocart** [comment]
Check your .htaccess file and the Rewrite_Base:

## SEO URL Settings
RewriteEngine On

RewriteBase /

May be in your case:
RewriteBase /cart

**Comment by Tangol** [comment]
Please note that I'm still experiencing the issue on https://github.com/nivocart/nivocart/commit/435280f6fb782d8aae444d35bb2625ca7e62336b , fresh install.

At installation, I've ticked the **enable SEO links** box and here's the result when I try to view any product.

![bug](https://user-images.githubusercontent.com/3336728/51064550-f192f400-1608-11e9-9d75-211afe504287.jpg)
![bug2](https://user-images.githubusercontent.com/3336728/51064552-f3f54e00-1608-11e9-838c-220f69de5973.jpg)

As you can see, the website was installed in a subfolder named **cart**.
However, the system automatically generates **car** in the **.htaccess** file.
It should be **cart**.

**Comment by nivocart** [comment]
I cannot reproduce this.

I use "RewriteBase /www/nivocart100/" on my local server, always have done, and everything is re-writing correctly. I also went through all the Seo_urls files and all seems fine, no unnecessary "trim" function in there.

Maybe try using a different path name to verify your findings.

**Comment by Tangol** [comment]
Found the cause.
It's related to the subfolder where you install NivoCart.
If the subfolder is named **cart** then you get the error.

Using any other name works fine (cart1, cart100, nivo, etc.)

Tested on: https://github.com/nivocart/nivocart/commit/084b075c65cffad3742b1c4450368ec2aafedcbf

**Comment by nivocart** [comment]
I am so glad you found the answer to this, as I just couldn't find anything wrong in the code.
I'm going to make a note of it in the forum.
Thank you!
