### ISSUE TITLE
OpenBay still in the code

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#9]
Please note that **OpenBay** still exists in the code.

https://github.com/nivocart/nivocart/search?q=OpenBay&unscoped_q=OpenBay

Tested on https://github.com/nivocart/nivocart/commit/90c68a70b6b9a1f5a6ef3d54ca4e3b6742e6668c

**Comment by nivocart** [comment]
Mostly done, just the permission left in the SQL to do ...
